# docker-compose-cpu.yml - CPU-Only version (no GPU required)
version: '3.8'

services:
  # Backend API service (CPU-only)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: agentos-backend-cpu
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Ensure CPU-only operation
      - CUDA_VISIBLE_DEVICES=""
      - OMP_NUM_THREADS=4
    restart: unless-stopped
    volumes:
      - ./qa_log.log:/app/qa_log.log
      - ./ideal_contract_templates:/app/ideal_contract_templates
      - ./chroma_db:/app/chroma_db

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: agentos-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    restart: unless-stopped
    depends_on:
      - backend
